-- =========================================
-- AuctionItemCategories
-- =========================================
INSERT INTO "AuctionItemCategories" ("Id", "Name", "CreatedAt", "UpdatedAt") VALUES
(1, 'スマートフォン・タブレット', NOW(), NOW()),
(2, 'PC関係', NOW(), NOW()),
(3, '生活家電', NOW(), NOW()),
(4, 'ゲーム', NOW(), NOW()),
(5, 'その他', NOW(), NOW());

-- =========================================
-- Products
-- =========================================
INSERT INTO "Products"
("Name", "Description", "ThumbnailImageUrl", "ImageUrl", "OriginalPrice", "CategoryId", "StockQuantity", "IsActive", "DurationMinutes", "CreatedAt", "UpdatedAt")
VALUES
('iPhone 14 Pro 128GB', 'Appleの最新スマートフォン。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 148000, 1, 10, TRUE, 120, NOW(), NOW()),
('iPhone 14 Pro Max 256GB', '大画面と高性能を両立。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 178000, 1, 8, TRUE, 120, NOW(), NOW()),
('iPhone 13 128GB', '前世代でもまだまだ高性能。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 108000, 1, 12, TRUE, 120, NOW(), NOW()),
('iPhone SE (第3世代)', '手のひらサイズで高性能。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 57800, 1, 15, TRUE, 120, NOW(), NOW()),
('iPad Pro 11インチ M2', '高性能タブレット。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 124800, 1, 10, TRUE, 120, NOW(), NOW()),
('iPad Air 第5世代', '軽量で高性能なiPad。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 92800, 1, 12, TRUE, 120, NOW(), NOW()),
('iPad mini 第6世代', 'コンパクトタブレット。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 72800, 1, 10, TRUE, 120, NOW(), NOW()),
('Galaxy S23 Ultra', 'Samsungのフラッグシップスマホ。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 168000, 1, 7, TRUE, 120, NOW(), NOW()),
('Galaxy Z Fold4', '折りたたみスマホの先駆け。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 238000, 1, 5, TRUE, 120, NOW(), NOW()),
('Galaxy Z Flip4', 'コンパクトに折り畳めるスマホ。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 148000, 1, 9, TRUE, 120, NOW(), NOW()),
('Google Pixel 7 Pro', 'Google純正の高性能スマホ。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 124000, 1, 10, TRUE, 120, NOW(), NOW()),
('Google Pixel 7a', 'コスパに優れたPixel。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 59800, 1, 15, TRUE, 120, NOW(), NOW()),
('Xperia 1 IV', 'Sonyのフラッグシップスマホ。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 148000, 1, 8, TRUE, 120, NOW(), NOW()),
('Xperia 5 IV', 'ハイエンドながらコンパクト。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 124800, 1, 10, TRUE, 120, NOW(), NOW()),
('AQUOS R7', '日本製ハイエンドスマホ。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 138000, 1, 7, TRUE, 120, NOW(), NOW()),
('OPPO Reno9 A', 'コスパ重視の人気モデル。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 39800, 1, 20, TRUE, 120, NOW(), NOW()),
('HUAWEI MatePad Pro', '高性能Androidタブレット。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 79800, 1, 12, TRUE, 120, NOW(), NOW()),
('Lenovo Tab P11 Pro', '有機EL搭載タブレット。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 59800, 1, 15, TRUE, 120, NOW(), NOW()),
('Surface Go 3', '小型Windowsタブレット。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 64800, 1, 10, TRUE, 120, NOW(), NOW()),
('Surface Pro 9', 'Windows 2-in-1タブレット。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 128000, 1, 10, TRUE, 120, NOW(), NOW()),
('Fire HD 10 タブレット', 'Amazon製大画面タブレット。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 19800, 1, 25, TRUE, 120, NOW(), NOW()),
('Fire HD 8 タブレット', 'コスパに優れたタブレット。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 12800, 1, 30, TRUE, 120, NOW(), NOW()),
('Kindle Paperwhite', '電子書籍リーダー。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 14800, 1, 20, TRUE, 120, NOW(), NOW()),
('Kindle Oasis', '高級電子書籍リーダー。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 29800, 1, 15, TRUE, 120, NOW(), NOW()),
('Xiaomi Pad 5', '高コスパAndroidタブレット。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 44800, 1, 18, TRUE, 120, NOW(), NOW()),
('Redmi Note 11', '格安でも十分な性能。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 24800, 1, 30, TRUE, 120, NOW(), NOW()),
('OPPO Find N2 Flip', '最新折りたたみスマホ。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 128000, 1, 6, TRUE, 120, NOW(), NOW()),
('ASUS ROG Phone 6', 'ゲーミングスマホ。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 99800, 1, 10, TRUE, 120, NOW(), NOW()),
('Nothing Phone (1)', 'デザイン性の高いスマホ。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 69800, 1, 12, TRUE, 120, NOW(), NOW()),
('Fairphone 4', 'サステナブル設計スマホ。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 79800, 1, 10, TRUE, 120, NOW(), NOW()),
('MacBook Air M2 13インチ', '軽量で高性能なAppleノートPC。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 148000, 2, 10, TRUE, 120, NOW(), NOW()),
('MacBook Pro 14インチ M2 Pro', 'クリエイター向けハイスペックノート。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 238000, 2, 6, TRUE, 120, NOW(), NOW()),
('MacBook Pro 16インチ M2 Max', '最強クラスのAppleノートPC。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 348000, 2, 4, TRUE, 120, NOW(), NOW()),
('Dell XPS 13 Plus', '高級感あるデザインのモバイルノート。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 168000, 2, 8, TRUE, 120, NOW(), NOW()),
('Dell XPS 15', 'パワフルな作業もこなせるノートPC。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 198000, 2, 7, TRUE, 120, NOW(), NOW()),
('Dell Alienware m15 R7', 'ゲーミングに特化したAlienwareノート。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 218000, 2, 6, TRUE, 120, NOW(), NOW()),
('HP Spectre x360 14', '2-in-1デザインの人気ノート。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 158000, 2, 9, TRUE, 120, NOW(), NOW()),
('HP Omen 16', '高性能ゲーミングノートPC。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 178000, 2, 6, TRUE, 120, NOW(), NOW()),
('Lenovo ThinkPad X1 Carbon', 'ビジネス向け定番ノート。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 168000, 2, 10, TRUE, 120, NOW(), NOW()),
('Lenovo Legion 5 Pro', 'ゲーミング向け高性能ノートPC。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 158000, 2, 7, TRUE, 120, NOW(), NOW()),
('ASUS ZenBook 14 OLED', '有機ELディスプレイ搭載ノート。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 128000, 2, 9, TRUE, 120, NOW(), NOW()),
('ASUS TUF Gaming A15', 'コスパの良いゲーミングノート。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 118000, 2, 12, TRUE, 120, NOW(), NOW()),
('Microsoft Surface Laptop 5', 'スリムでおしゃれなノートPC。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 148000, 2, 8, TRUE, 120, NOW(), NOW()),
('Microsoft Surface Pro 9', 'タブレットにもなる2-in-1。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 138000, 2, 10, TRUE, 120, NOW(), NOW()),
('Razer Blade 15', 'スタイリッシュなゲーミングノート。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 228000, 2, 5, TRUE, 120, NOW(), NOW()),
('Razer Blade 17', '大画面ゲーミングノートPC。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 268000, 2, 4, TRUE, 120, NOW(), NOW()),
('Acer Swift 5', '薄型軽量のモバイルノート。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 108000, 2, 11, TRUE, 120, NOW(), NOW()),
('Acer Predator Helios 300', 'ハイスペックゲーミングノート。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 158000, 2, 7, TRUE, 120, NOW(), NOW()),
('MSI Prestige 14', 'クリエイター向けノートPC。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 138000, 2, 9, TRUE, 120, NOW(), NOW()),
('MSI GE76 Raider', 'ゲーマー御用達の大型ノートPC。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 228000, 2, 5, TRUE, 120, NOW(), NOW()),
('自作PCキット Ryzen 7 + RTX 3060', 'ゲーミング向け自作PCキット。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 148000, 2, 12, TRUE, 120, NOW(), NOW()),
('自作PCキット i7 + RTX 3070', 'ミドルハイクラスの自作PCセット。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 178000, 2, 10, TRUE, 120, NOW(), NOW()),
('自作PCキット i9 + RTX 4080', 'ハイエンドゲーミングPC用キット。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 278000, 2, 6, TRUE, 120, NOW(), NOW()),
('ゲーミングモニター 27インチ 144Hz', '高リフレッシュレートのIPSモニター。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 39800, 2, 20, TRUE, 60, NOW(), NOW()),
('ゲーミングモニター 32インチ 165Hz', '迫力ある大画面モニター。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 49800, 2, 15, TRUE, 60, NOW(), NOW()),
('メカニカルキーボード RGB', 'ゲーマー向けメカニカルキーボード。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 12800, 2, 25, TRUE, 60, NOW(), NOW()),
('ゲーミングマウス Logicool G Pro', 'プロ仕様の軽量ゲーミングマウス。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 9800, 2, 30, TRUE, 60, NOW(), NOW()),
('外付けSSD 1TB', '高速な外付けSSD。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 12800, 2, 30, TRUE, 60, NOW(), NOW()),
('外付けHDD 4TB', '大容量の外付けHDD。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 10800, 2, 25, TRUE, 60, NOW(), NOW()),
('Wi-Fi 6ルーター', '最新規格対応の高速Wi-Fiルーター。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 15800, 2, 20, TRUE, 60, NOW(), NOW()),
('Dyson V15 Detect', 'コードレス掃除機の最新モデル。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 79800, 3, 10, TRUE, 120, NOW(), NOW()),
('Panasonic NA-VX9900', '全自動ドラム式洗濯乾燥機。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 198000, 3, 5, TRUE, 180, NOW(), NOW()),
('Toshiba ER-SS70', '高性能冷蔵庫。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 128000, 3, 8, TRUE, 180, NOW(), NOW()),
('Sharp Healsio AX-X10', '自動調理機能付きオーブン。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 79800, 3, 12, TRUE, 120, NOW(), NOW()),
('Hitachi Kurobe', '高性能エアコン。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 98000, 3, 10, TRUE, 120, NOW(), NOW()),
('BALMUDA The Toaster', '話題の高級トースター。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 39800, 3, 15, TRUE, 60, NOW(), NOW()),
('Iris Ohyama EC-AC85', 'サイクロン掃除機。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 19800, 3, 20, TRUE, 60, NOW(), NOW()),
('Vitantonio ワッフルメーカー', '手軽にワッフルを焼ける。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 8800, 3, 25, TRUE, 60, NOW(), NOW()),
('象印 電気ポット CD-WB30', '使いやすい電気ケトル。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 7980, 3, 30, TRUE, 60, NOW(), NOW()),
('象印 炊飯器 NP-VI10', '多機能炊飯器。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 29800, 3, 20, TRUE, 120, NOW(), NOW()),
('Panasonic EH-NA0B', 'ナノケアドライヤー。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 29800, 3, 15, TRUE, 60, NOW(), NOW()),
('Sharp ES-G110', '衣類乾燥機付き洗濯機。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 88000, 3, 8, TRUE, 180, NOW(), NOW()),
('T-fal インジニオ・ネオ', '多機能フライパンセット。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 12000, 3, 25, TRUE, 60, NOW(), NOW()),
('Panasonic NC-A56', '自動コーヒーメーカー。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 15800, 3, 20, TRUE, 60, NOW(), NOW()),
('アイリスオーヤマ ホットカーペット', '電気式ホットカーペット。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 9800, 3, 30, TRUE, 120, NOW(), NOW()),
('象印 電気ケトル CK-PA10', '素早く湯を沸かせる電気ケトル。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 5980, 3, 30, TRUE, 60, NOW(), NOW()),
('Vitantonio ホットサンドメーカー', '朝食に便利なホットサンドメーカー。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 8800, 3, 20, TRUE, 60, NOW(), NOW()),
('Panasonic EH-NA9A', '最新ナノケアドライヤー。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 32800, 3, 15, TRUE, 60, NOW(), NOW()),
('Sharp KS-G32E', '衣類乾燥機。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 39800, 3, 10, TRUE, 120, NOW(), NOW()),
('Dyson Purifier Cool', '空気清浄機能付き扇風機。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 59800, 3, 12, TRUE, 60, NOW(), NOW()),
('Panasonic SR-HX101', '高性能炊飯器。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 24800, 3, 20, TRUE, 120, NOW(), NOW()),
('アイリスオーヤマ IHクッキングヒーター', '卓上IHヒーター。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 19800, 3, 15, TRUE, 60, NOW(), NOW()),
('BALMUDA The Range', '高性能電子レンジ。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 49800, 3, 10, TRUE, 120, NOW(), NOW()),
('T-fal 電気ケトル ジャスティン', '素早く沸く電気ケトル。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 4980, 3, 25, TRUE, 60, NOW(), NOW()),
('象印 ホットプレート EA-GV35', '家族で使えるホットプレート。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 19800, 3, 20, TRUE, 120, NOW(), NOW()),
('Panasonic NV-SJ105', '全自動洗濯機。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 128000, 3, 10, TRUE, 180, NOW(), NOW()),
('Dyson Supersonic', '高性能ヘアドライヤー。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 49800, 3, 15, TRUE, 60, NOW(), NOW()),
('Sharp EC-SX100', 'サイクロン掃除機。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 29800, 3, 10, TRUE, 60, NOW(), NOW()),
('Panasonic EH-NA0J', 'ナノケアドライヤー旧モデル。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 19800, 3, 15, TRUE, 60, NOW(), NOW()),
('BALMUDA The Kettle', 'おしゃれな電気ケトル。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 19800, 3, 10, TRUE, 60, NOW(), NOW()),
('Nintendo Switch OLED', '最新モデルのSwitch。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 39800, 4, 15, TRUE, 60, NOW(), NOW()),
('PlayStation 5', '次世代ゲーム機PS5。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 54800, 4, 10, TRUE, 60, NOW(), NOW()),
('Xbox Series X', '最新型Xbox。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 54800, 4, 8, TRUE, 60, NOW(), NOW()),
('Nintendo Switch Lite', '小型のSwitch。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 19800, 4, 20, TRUE, 60, NOW(), NOW()),
('PS4 Pro', '高性能PS4。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 34800, 4, 12, TRUE, 60, NOW(), NOW()),
('ゲーム用ゲーミングチェア', '快適なゲーミングチェア。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 19800, 4, 15, TRUE, 60, NOW(), NOW()),
('Razer Huntsman V2', 'ゲーミングキーボード。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 19800, 4, 20, TRUE, 60, NOW(), NOW()),
('Logicool G Pro Wireless', 'ゲーミングマウス。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 9800, 4, 30, TRUE, 60, NOW(), NOW()),
('Switch用リングフィットアドベンチャー', '運動もできるゲーム。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 7980, 4, 25, TRUE, 60, NOW(), NOW()),
('PS VR2', 'VRゲーム体験用デバイス。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 59800, 4, 10, TRUE, 60, NOW(), NOW()),
('ゼルダの伝説 ブレス オブ ザ ワイルド', 'Switch用アクションRPG。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 7980, 4, 30, TRUE, 60, NOW(), NOW()),
('スーパーマリオ 3Dワールド', 'Switch用マリオアクションゲーム。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 5980, 4, 25, TRUE, 60, NOW(), NOW()),
('モンスターハンターライズ', 'Switch用ハンティングアクションゲーム。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 7980, 4, 20, TRUE, 60, NOW(), NOW()),
('スプラトゥーン3', '人気のオンラインシューティングゲーム。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 5980, 4, 30, TRUE, 60, NOW(), NOW()),
('ポケットモンスター スカーレット', '人気RPGシリーズ最新作。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 5980, 4, 25, TRUE, 60, NOW(), NOW()),
('ポケットモンスター バイオレット', 'ポケモン最新作。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 5980, 4, 25, TRUE, 60, NOW(), NOW()),
('ファイナルファンタジーVII リメイク', 'PS5用RPG。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 7980, 4, 15, TRUE, 60, NOW(), NOW()),
('龍が如く7 光と闇の行方', 'PS5用アクションRPG。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 6980, 4, 15, TRUE, 60, NOW(), NOW()),
('Ghost of Tsushima', '侍アクションゲーム。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 5980, 4, 20, TRUE, 60, NOW(), NOW()),
('Bloodborne', 'ダークアクションRPG。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 4980, 4, 15, TRUE, 60, NOW(), NOW()),
('エーペックスレジェンズ', 'バトルロイヤルFPS。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 0, 4, 30, TRUE, 60, NOW(), NOW()),
('フォートナイト', '人気オンラインバトルロイヤルゲーム。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 0, 4, 30, TRUE, 60, NOW(), NOW()),
('Minecraft', 'サンドボックスゲームの定番。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 2980, 4, 40, TRUE, 60, NOW(), NOW()),
('テイルズ オブ アライズ', 'アクションRPG。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 5980, 4, 20, TRUE, 60, NOW(), NOW()),
('鬼滅の刃 ヒノカミ血風譚', '格闘アクションゲーム。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 7980, 4, 20, TRUE, 60, NOW(), NOW()),
('スマブラSP', '大乱闘スマッシュブラザーズ。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 5980, 4, 25, TRUE, 60, NOW(), NOW()),
('ゼノブレイド3', 'Switch用RPG。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 7980, 4, 15, TRUE, 60, NOW(), NOW()),
('リングフィットアドベンチャー', '運動もできるRPG。', '/assets/image-sample.png', '/assets/image-sample.png', 7980, 4, 20, TRUE, 60, NOW(), NOW()),
('モンスターハンターワールド', 'アクションハンティングゲーム。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 5980, 4, 15, TRUE, 60, NOW(), NOW()),
('ゼルダの伝説 ティアーズ オブ ザ キングダム', '最新アクションRPG。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 7980, 4, 20, TRUE, 60, NOW(), NOW()),
('キャンプ用テント', '2~3人用テント。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 14800, 5, 15, TRUE, 120, NOW(), NOW()),
('アウトドアチェア', '折りたたみ式キャンプチェア。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 2980, 5, 20, TRUE, 120, NOW(), NOW()),
('寝袋 マミー型', '軽量コンパクト寝袋。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 5980, 5, 25, TRUE, 120, NOW(), NOW()),
('折りたたみ自転車', '通勤・アウトドアに便利。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 19800, 5, 10, TRUE, 120, NOW(), NOW()),
('防災セット', '災害時に役立つ防災セット。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 9800, 5, 20, TRUE, 120, NOW(), NOW()),
('寝袋 シュラフタイプ', 'キャンプ用寝袋。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 4980, 5, 25, TRUE, 120, NOW(), NOW()),
('ヘッドランプ LED', '夜間作業やキャンプに便利。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 2980, 5, 20, TRUE, 60, NOW(), NOW()),
('アウトドア調理セット', 'バーベキューやキャンプに。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 5980, 5, 15, TRUE, 120, NOW(), NOW()),
('携帯浄水器', '登山・アウトドアに便利。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 3980, 5, 20, TRUE, 120, NOW(), NOW()),
('折りたたみテーブル', 'コンパクト収納可能なテーブル。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 4980, 5, 25, TRUE, 120, NOW(), NOW()),
('キャンプ用焚き火台', '安全に焚き火ができる台。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 5980, 5, 15, TRUE, 120, NOW(), NOW()),
('ポータブルバッテリー 20000mAh', 'アウトドアでも安心。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 5980, 5, 30, TRUE, 60, NOW(), NOW()),
('折りたたみ自転車 MTB', '軽量コンパクトなマウンテンバイク。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 24800, 5, 10, TRUE, 120, NOW(), NOW()),
('防水バックパック 30L', '登山・アウトドア用。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 7980, 5, 20, TRUE, 120, NOW(), NOW()),
('トレッキングポール 2本セット', '登山やトレッキング用。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 3980, 5, 25, TRUE, 120, NOW(), NOW()),
('ポータブルチェア', '軽量で持ち運びやすい椅子。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 2980, 5, 30, TRUE, 60, NOW(), NOW()),
('焚き火用グローブ', '耐熱性グローブ。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 1980, 5, 40, TRUE, 60, NOW(), NOW()),
('アウトドア用ナイフ', '多用途アウトドアナイフ。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 2980, 5, 30, TRUE, 60, NOW(), NOW()),
('ポータブルクーラーボックス', '飲料・食材の保冷に。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 5980, 5, 20, TRUE, 120, NOW(), NOW()),
('折りたたみカヤック', '小型カヤック。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 59800, 5, 5, TRUE, 180, NOW(), NOW()),
('アウトドア用テントライト', '夜間照明用。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 1980, 5, 30, TRUE, 60, NOW(), NOW()),
('携帯用ガスコンロ', 'コンパクトなガスコンロ。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 3980, 5, 20, TRUE, 60, NOW(), NOW()),
('防水スマホケース', '雨天・アウトドア用。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 1980, 5, 50, TRUE, 60, NOW(), NOW()),
('ポータブルソーラーパネル', 'アウトドアで充電可能。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 7980, 5, 15, TRUE, 120, NOW(), NOW()),
('アウトドア用ランタン', 'LEDランタン。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 3980, 5, 25, TRUE, 60, NOW(), NOW()),
('キャンピングマット', '寝心地の良いマット。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 2980, 5, 30, TRUE, 60, NOW(), NOW()),
('アウトドア用調理鍋', '軽量調理鍋。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 1980, 5, 25, TRUE, 60, NOW(), NOW()),
('防災ラジオ', 'LEDライト・ラジオ・手回し充電。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 2980, 5, 20, TRUE, 60, NOW(), NOW()),
('多機能ツールナイフ', 'アウトドア・防災用。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 1980, 5, 25, TRUE, 60, NOW(), NOW()),
('携帯用浄水ボトル', 'いつでも水を浄化可能。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 2980, 5, 30, TRUE, 60, NOW(), NOW()),
('折りたたみハンモック', '軽量で携帯可能。', '/assets/thumbnail-sample.png', '/assets/image-sample.png', 3980, 5, 20, TRUE, 120, NOW(), NOW());