CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AuctionItemCategories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Description" character varying(255) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuctionItemCategories" PRIMARY KEY ("Id")
);

CREATE TABLE "Campaigns" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(255),
    "StartsAt" timestamp with time zone,
    "EndsAt" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Campaigns" PRIMARY KEY ("Id")
);

CREATE TABLE "FailedLoginAttempts" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IpAddress" character varying(45) NOT NULL,
    "Email" character varying(256) NOT NULL,
    "AttemptedAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_FailedLoginAttempts" PRIMARY KEY ("Id")
);

CREATE TABLE "PointPlans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Points" integer NOT NULL,
    "Price" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PointPlans" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(255) NOT NULL,
    "PasswordHash" character varying(64) NOT NULL,
    "PasswordSalt" character varying(64) NOT NULL,
    "Username" character varying(50) NOT NULL,
    "LastLoginAt" timestamp with time zone,
    "LastFailedLoginAt" timestamp with time zone,
    "FailedLoginCount" integer NOT NULL,
    "EmailConfirmed" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "IsBotUser" boolean NOT NULL,
    "PointBalance" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "ThumbnailImageUrl" character varying(512) NOT NULL,
    "ImageUrl" character varying(512) NOT NULL,
    "StartingBid" bigint NOT NULL,
    "MinimumPrice" bigint NOT NULL,
    "BidIncrement" bigint NOT NULL,
    "OriginalPrice" bigint NOT NULL,
    "CategoryId" integer NOT NULL,
    "StockQuantity" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "DurationMinutes" integer NOT NULL,
    "BidPointCost" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_AuctionItemCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "AuctionItemCategories" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Notifications" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer,
    "Category" character varying(50),
    "Title" character varying(120) NOT NULL,
    "Message" character varying(500) NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "PointBalanceLots" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "QuantityRemaining" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PointBalanceLots" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PointBalanceLots_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "PointPurchases" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Points" integer NOT NULL,
    "AmountPaid" integer NOT NULL,
    "Note" character varying(255),
    "ExternalTokenJti" character varying(64),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PointPurchases" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PointPurchases_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "AuctionItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer,
    "Name" character varying(255) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "ThumbnailImageUrl" character varying(512) NOT NULL,
    "ImageUrl" character varying(512) NOT NULL,
    "OriginalPrice" bigint NOT NULL,
    "StartingBid" bigint NOT NULL,
    "MinimumPrice" bigint NOT NULL,
    "BidIncrement" bigint NOT NULL,
    "CurrentPrice" bigint NOT NULL,
    "TotalBidCost" bigint NOT NULL,
    "CategoryId" integer NOT NULL,
    "CurrentHighestBidUserId" integer,
    "EndTime" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    "BidPointCost" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuctionItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AuctionItems_AuctionItemCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "AuctionItemCategories" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AuctionItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AuctionItems_Users_CurrentHighestBidUserId" FOREIGN KEY ("CurrentHighestBidUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "AuctionItemPurchases" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "AuctionItemId" integer NOT NULL,
    "Prefecture" character varying(32) NOT NULL,
    "City" character varying(64) NOT NULL,
    "AddressLine1" character varying(128) NOT NULL,
    "AddressLine2" character varying(128),
    "DeliveryDate" date NOT NULL,
    "DeliveryTimeSlot" integer NOT NULL,
    "ShippingCarrier" integer NOT NULL,
    "DepositTokenJti" character varying(64) NOT NULL,
    "DepositAmount" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuctionItemPurchases" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AuctionItemPurchases_AuctionItems_AuctionItemId" FOREIGN KEY ("AuctionItemId") REFERENCES "AuctionItems" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AuctionItemPurchases_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Bids" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AuctionItemId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "BidAmount" bigint NOT NULL,
    "BidTime" timestamp with time zone NOT NULL,
    "IpAddress" character varying(45) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Bids" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Bids_AuctionItems_AuctionItemId" FOREIGN KEY ("AuctionItemId") REFERENCES "AuctionItems" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Bids_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "PointTransactions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Type" integer NOT NULL,
    "TotalAmount" integer NOT NULL,
    "BalanceAfter" integer NOT NULL,
    "CampaignId" integer,
    "PointPurchaseId" integer,
    "BidId" integer,
    "Note" character varying(255),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PointTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PointTransactions_Bids_BidId" FOREIGN KEY ("BidId") REFERENCES "Bids" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PointTransactions_Campaigns_CampaignId" FOREIGN KEY ("CampaignId") REFERENCES "Campaigns" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PointTransactions_PointPurchases_PointPurchaseId" FOREIGN KEY ("PointPurchaseId") REFERENCES "PointPurchases" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PointTransactions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "PointTransactionEntries" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PointTransactionId" bigint NOT NULL,
    "Quantity" integer NOT NULL,
    "PointBalanceLotId" bigint NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "TotalPrice" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PointTransactionEntries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PointTransactionEntries_PointBalanceLots_PointBalanceLotId" FOREIGN KEY ("PointBalanceLotId") REFERENCES "PointBalanceLots" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PointTransactionEntries_PointTransactions_PointTransactionId" FOREIGN KEY ("PointTransactionId") REFERENCES "PointTransactions" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_AuctionItemCategories_Name" ON "AuctionItemCategories" ("Name");

CREATE UNIQUE INDEX "IX_AuctionItemPurchases_AuctionItemId" ON "AuctionItemPurchases" ("AuctionItemId");

CREATE UNIQUE INDEX "IX_AuctionItemPurchases_DepositTokenJti" ON "AuctionItemPurchases" ("DepositTokenJti");

CREATE INDEX "IX_AuctionItemPurchases_UserId" ON "AuctionItemPurchases" ("UserId");

CREATE INDEX "IX_AuctionItems_CategoryId" ON "AuctionItems" ("CategoryId");

CREATE INDEX "IX_AuctionItems_CurrentHighestBidUserId" ON "AuctionItems" ("CurrentHighestBidUserId");

CREATE INDEX "IX_AuctionItems_ProductId" ON "AuctionItems" ("ProductId");

CREATE UNIQUE INDEX "IX_Bids_AuctionItemId_BidAmount" ON "Bids" ("AuctionItemId", "BidAmount");

CREATE INDEX "IX_Bids_UserId" ON "Bids" ("UserId");

CREATE INDEX "IX_Notifications_UserId_CreatedAt" ON "Notifications" ("UserId", "CreatedAt");

CREATE INDEX "IX_PointBalanceLots_UserId_CreatedAt" ON "PointBalanceLots" ("UserId", "CreatedAt");

CREATE UNIQUE INDEX "IX_PointPurchases_ExternalTokenJti" ON "PointPurchases" ("ExternalTokenJti");

CREATE INDEX "IX_PointPurchases_UserId_CreatedAt" ON "PointPurchases" ("UserId", "CreatedAt");

CREATE INDEX "IX_PointTransactionEntries_PointBalanceLotId" ON "PointTransactionEntries" ("PointBalanceLotId");

CREATE INDEX "IX_PointTransactionEntries_PointTransactionId" ON "PointTransactionEntries" ("PointTransactionId");

CREATE INDEX "IX_PointTransactions_BidId" ON "PointTransactions" ("BidId");

CREATE INDEX "IX_PointTransactions_CampaignId" ON "PointTransactions" ("CampaignId");

CREATE INDEX "IX_PointTransactions_PointPurchaseId" ON "PointTransactions" ("PointPurchaseId");

CREATE INDEX "IX_PointTransactions_UserId_CreatedAt" ON "PointTransactions" ("UserId", "CreatedAt");

CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");

CREATE INDEX "IX_Products_IsActive" ON "Products" ("IsActive");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250914125414_InitialCreate', '10.0.0-preview.7.25380.108');

COMMIT;

